//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

type permEntry struct {
	Key   string
	Value int64
}

func main() {
	repoRoot, err := findRepoRoot()
	if err != nil {
		log.Fatalf("failed to find repo root: %v", err)
	}

	tsPath := filepath.Join(repoRoot, "seerr_permissions.ts")
	content, err := os.ReadFile(tsPath)
	if err != nil {
		log.Fatalf("failed to read seerr_permissions.ts: %v", err)
	}

	enumRegex := regexp.MustCompile(`(?m)^\s*([A-Z0-9_]+)\s*=\s*([0-9]+)\s*,?`)
	matches := enumRegex.FindAllStringSubmatch(string(content), -1)

	var entries []permEntry
	for _, match := range matches {
		if len(match) == 3 {
			name := match[1]
			if name == "NONE" {
				continue
			}
			val, err := strconv.ParseInt(match[2], 10, 64)
			if err != nil {
				log.Fatalf("failed to parse int value for %s: %v", name, err)
			}
			key := strings.ToLower(name)
			entries = append(entries, permEntry{Key: key, Value: val})
		}
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Value < entries[j].Value
	})

	var buf bytes.Buffer
	buf.WriteString("// Code generated by tools/gen_permissions.go from seerr_permissions.ts. DO NOT EDIT.\n\n")
	buf.WriteString("package provider\n\n")
	buf.WriteString("// PermissionsMap maps snake_case permission names to their bitmask integer values.\n")
	buf.WriteString("var PermissionsMap = map[string]int64{\n")
	for _, entry := range entries {
		buf.WriteString(fmt.Sprintf("\t%q: %d,\n", entry.Key, entry.Value))
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("failed to format generated code: %v\n%s", err, buf.String())
	}

	targetPath := filepath.Join(repoRoot, "internal", "provider", "permissions_gen.go")
	if err := os.WriteFile(targetPath, formatted, 0644); err != nil {
		log.Fatalf("failed to write %s: %v", targetPath, err)
	}

	fmt.Printf("Successfully generated %s (%d permissions)\n", targetPath, len(entries))
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	return "", fmt.Errorf("go.mod not found in parent directories")
}
